const trending = [
  {
    id: 1,
    title: "Mountain Hiking Tour",
    activities: "Hiking Tour | Stoke on Trent",
    price: 895,
    rating: 4.9,
    ratingCount: 180,
    duration: 8,
    freeCancelation: true,
    new: true,
    imgUrl: "images/trending/mountain.png",
    alt: "Mountain",
    discount: 30,
    wishlist: true,
  },
  {
    id: 2,
    title: "Train Tour Skyline",
    activities: "Hiking Tour | Stoke on Trent",
    price: 500,
    rating: 4.8,
    ratingCount: 180,
    duration: 12,
    freeCancelation: true,
    new: false,
    imgUrl: "images/trending/train.png",
    alt: "Train",
    discount: 15,
    wishlist: false,
  },
  {
    id: 3,
    title: "Forest Wild Life",
    activities: "Hiking Tour | Stoke on Trent",
    price: 895,
    rating: 4.4,
    ratingCount: 180,
    duration: 6,
    freeCancelation: true,
    new: true,
    imgUrl: "images/trending/forest.png",
    alt: "Forest",
    discount: 0,
    wishlist: false,
  },
  {
    id: 4,
    title: "Cultural highlights round trip",
    activities: "Hiking Tour | Stoke on Trent",
    price: 1400,
    rating: 4.9,
    ratingCount: 180,
    duration: 10,
    freeCancelation: true,
    new: false,
    imgUrl: "images/trending/cultural.png",
    alt: "Cultural",
    discount: 0,
    wishlist: false,
  },
  {
    id: 5,
    title: "Deep sea snorkel",
    activities: "Hiking Tour | Stoke on Trent",
    price: 1200,
    rating: 4.8,
    ratingCount: 180,
    duration: 5,
    freeCancelation: true,
    new: false,
    imgUrl: "images/trending/snorkel.png",
    alt: "Sea",
    discount: 10,
    wishlist: false,
  },
];

export default trending;
